# Generated by Django 2.1.4 on 2020-02-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('cardnumber', models.TextField(max_length=500)),
                ('phonenumber', models.TextField(max_length=50)),
                ('created', models.TextField(max_length=500)),
                ('token', models.TextField(max_length=500)),
            ],
        ),
    ]
