# Generated by Django 2.1.4 on 2020-02-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='price',
        ),
    ]
