# Generated by Django 2.1.4 on 2020-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='city',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='token',
        ),
        migrations.AlterField(
            model_name='datalist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
