# Generated by Django 2.1.4 on 2020-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0002_auto_20200223_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='cardnumber',
            field=models.TextField(default='5105105105105100', max_length=500),
        ),
        migrations.AddField(
            model_name='datalist',
            name='city',
            field=models.CharField(default='LA', max_length=50),
        ),
        migrations.AddField(
            model_name='datalist',
            name='created',
            field=models.TextField(default='Sun, 23 Feb 2020 08:18:51 GMT', max_length=500),
        ),
        migrations.AddField(
            model_name='datalist',
            name='phonenumber',
            field=models.TextField(default='(319)-883-4480', max_length=50),
        ),
        migrations.AddField(
            model_name='datalist',
            name='token',
            field=models.TextField(default='7f38e7a645fbd1b3c68fbc75ecd62d24', max_length=500),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='name',
            field=models.CharField(default='User0', max_length=50),
        ),
    ]
